title: blank
first_name: Shreyas
middle_name:
last_name: Swaminathan
email: sks282 (at) cornell (dot) edu
description: >-
  Personal website for Shreyas Swaminathan, a PhD student in Statistics at
  Cornell University.
keywords: statistics, probability, mathematics, computer science, shreyas swaminathan
lang: en
url: https://skswaminathan.github.io
baseurl:

navbar_fixed: true
back_to_top: true
enable_darkmode: true
enable_progressbar: true
max_width: 930px

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

include:
  - _pages

exclude:
  - .bundle/
  - .jekyll-cache/
  - .sass-cache/
  - vendor/

keep_files:
  - CNAME
  - .nojekyll

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: assets
    values:
      sitemap: false
